### ISSUE TITLE
Add some test

### ISSUE THREAD

**Issue by jyz0309** [vesoft-inc/nebula-importer#145]
I find that this project have a little test file (just 2 `xx_test.go`files). How about add some tests? Maybe I can help you :)

**Comment by wey-gu** [comment]
Thank you @jyz0309 as always :-D.

@jievince could you please help comment on this?

**Comment by jievince** [comment]
@jyz0309  Thank you very much. You can add a pr to enrich our tests

**Comment by wey-gu** [comment]
Will close it as it's been inactive for days. Feel free to reopen it.
