### ISSUE TITLE
The bash dir path `failDataPath` related is project root but not config root when using a remote URL

### ISSUE THREAD

**Issue by 1uvu** [vesoft-inc/nebula-importer#151]
When I **call the Runner of the importer as the library** and **import a csv file using remote url**, `failDataPath` related a **mistake bash path**.
The error case:
![err](https://user-images.githubusercontent.com/47083415/125267321-44180d00-e339-11eb-9be1-a8b8efa554ea.png)
The normal case:
![norm](https://user-images.githubusercontent.com/47083415/125267431-61e57200-e339-11eb-8f62-af8af72bd87b.png)

**Comment by wey-gu** [comment]
Dear @1uvu, thank you for reporting this.

@jievince from my understanding a value that is not a POSIX path was not initially intended to be supported/ considered, now it seems it's verified by @1uvu it's supported, but, with an unexpected behavior that the `failDataPath` was not properly handled then. Am I understanding it right?

If that is the case we can fix this or update docs for it?
