### ISSUE TITLE
If the space does not exist, the program is suspended.

### ISSUE THREAD

**Issue by zhilinglike** [vesoft-inc/nebula-importer#154]
![image](https://user-images.githubusercontent.com/87118380/126583798-7195d646-a6ff-4849-a72b-14ec4d5c5b5d.png)

The importer cannot exit.

**Comment by wey-gu** [comment]
@jievince could you help take a look?

**Comment by jievince** [comment]
Please add more information

**Comment by jievince** [comment]
Yes, currently this is expected behaviour. Before import data, you need to ensure that the schema is ready and correct.
