### ISSUE TITLE
wrong method name

### ISSUE THREAD

**Issue by 1991Troy** [vesoft-inc/nebula-importer#179]
2021/11/25 18:28:43 --- START OF NEBULA IMPORTER ---
2021/11/25 18:28:44 failed to open connection, error: failed to verify client version: verifyClientVersion failed: wrong method name
2021/11/25 18:28:45 --- END OF NEBULA IMPORTER ---
exit status 200

version: v2
description: example
removeTempFiles: false
clientSettings:
  retry: 3
  concurrency: 1 # number of graph clients
  channelBufferSize: 128
  space: test
  connection:
    user: root
    password: password
    address: *****
logPath: ./err/test.log

nebula version 2.5.0

**Comment by 1991Troy** [comment]
**Since I use nebula-graph v2.5.0, when I change to nebula-importer v2.5.0 **
https://github.com/vesoft-inc/nebula-importer/releases

**error:**
go: downloading github.com/vesoft-inc/nebula-go/v2 v2.5.0
github.com/vesoft-inc/nebula-importer/pkg/client imports
        github.com/vesoft-inc/nebula-go/v2: github.com/vesoft-inc/nebula-go/v2@v2.5.0: verifying module: checksum mismatch
        downloaded: h1:7w3bUYTAtvEA20go5XFoEDx5HbnzlOgo5VBSP3AvXtE=
        sum.golang.org: h1:A4wZoGqR1W1mQ9y/X+tV1wCMIsDkuhFMthTQKMeT8Yc=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.

**I seek for go mod tidy
go clean -modcache
go mod tidy**
not solved 
if I use go mod init, it will change to nebula-importer v2.6.0

**Comment by 1991Troy** [comment]
https://github.com/vesoft-inc/nebula-go，mentioned
NOTE Installing Nebula Go v2.5.0 could cause checksum mismatch, use v2.5.1 instead.
！！！！！！！
v2.5.1 works for me

**Comment by wey-gu** [comment]
Sorry just saw this issue, as talked via forum, will close it and we should improve the error message, reported in #180

**Comment by hjing100** [comment]
我的报错类似：
failed to open connection, error: incompatible version between client and server: Graph client version(3.0.0) is not accepted, current graph client white list: 2.6.2:2.5.0:2.5.1:2.6.0.

**Comment by hjing100** [comment]
我是nebula-importer和nebula graph版本不一致造成的。

因为我不是git clone的，而是直接到GitHub下载的，所以下载的是3.0.0版本的importer，和nebula graph的版本不匹配。
然后我用git clone -b v2.6.0 https://github.com/vesoft-inc/nebula-importer.git，问题解决。
