### ISSUE TITLE
failed to open connection, error: failed to open transport, error: dial tcp 127.0.0.1:3699: connect: connection refused

### ISSUE THREAD

**Issue by hjing100** [vesoft-inc/nebula-importer#195]
执行./nebula-importer --config config.yaml 报错：
failed to open connection, error: failed to open transport, error: dial tcp 127.0.0.1:3699: connect: connection refused

是根据知乎上的 使用图数据库 Nebula Graph 数据导入快速体验知识图谱 OwnThink

**Comment by hjing100** [comment]
改成address: 127.0.0.1:9669

**Comment by wey-gu** [comment]
Yes, 3699 was the old default graphD port in v1 whereas in v2 it's 9669 :)

**Comment by 0704li** [comment]
Hello, I'm having the same issue now. How do I fix this?
![Uploading 屏幕截图 2024-08-15 181058.png…]()
