### ISSUE TITLE
Adjust wait time on Retry

### ISSUE THREAD

**Issue by cangfengzhs** [vesoft-inc/nebula-importer#216]
https://github.com/vesoft-inc/nebula-importer/blob/e7281ccc8a1af64c9769743ff937cec4f26bc0e4/pkg/client/clientpool.go#L181

In case of write failure, in order to avoid avalanche, the waiting time here is better to increase exponentially, because it is likely that the write speed is too fast, causing the WAL of the storage to be full.

**Comment by veezhang** [comment]
fixed
