### ISSUE TITLE
I want import this repo into my project, but here don't marked v3 at go.mod, how could I use it?

### ISSUE THREAD

**Issue by LooJee** [vesoft-inc/nebula-importer#232]
**General Question**

I want import this repo into my project, but only v1 can be imported.

<img width="443" alt="image" src="https://user-images.githubusercontent.com/13059033/204991523-d11ffe9e-5ae2-4e34-9fe4-49a6cc36a100.png">

maybe should modify module to v3?

![image](https://user-images.githubusercontent.com/13059033/204992198-f883f3c3-0ea6-4419-9a52-2f95438746c5.png)

**Comment by wey-gu** [comment]
You could refer to https://github.com/vesoft-inc/nebula-studio/tree/master/server :)

**Comment by LooJee** [comment]
@wey-gu I tried it, but this version (v1.0.1-0.20220719030708-8e376665042e) cannot inject my logger, so I switch to (v1.0.1-0.20221028024308-3cd1335b9502) which I find in the git history of nebula-studio. Or maybe you can refer me to the latest version?

**Comment by wey-gu** [comment]
@LooJee you already figured out how to do that? Feel free to share it here or elsewhere :)

**Comment by LooJee** [comment]
@wey-gu Hi, we may have some customized features, I will do these on the forked one temporarily. Thank you all release the awesome product.
