### ISSUE TITLE
Support concat for VID

### ISSUE THREAD

**Issue by veezhang** [vesoft-inc/nebula-importer#244]
**Introduction**

Support concat with constant, field or mixed for VID.

**Contents**

**Related work**

**Comment by wey-gu** [comment]
If we support this, a lot of **Transform Work** will be no longer needed(it will be extremely friendly to users!❤️), and we could extend its concat capability to vids and any other columns.

**Comment by wey-gu** [comment]
> @wey-gu I feel that the props should be split as small as possible. Is it necessary to support concat for props?

If from implementation perspective, it's a lot of effort to do so, I am not sure if it's necessary, as the reason I would like to request concat was on VID. But there could be the such need, for instance, just in case, we have First name, Last name col in data source and would like to have Name as prop :-D
