### ISSUE TITLE
panic when retry is zero

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-importer#251]
We have bunch of errors that are not properly handled and reported, users are quite confusing on where could be wrong, especially for those who are new to NebulaGraph and/or importer.

https://discuss.nebula-graph.com.cn/t/topic/11677?u=wey

**Comment by wey-gu** [comment]
I have been seeing a lot of too-good-to-be-true great improvements and features brought by you @veezhang already :).

You are always amazing!

So I want to give this(there in my mind for long time) a try/issue :)

**Comment by veezhang** [comment]
@wey-gu Thanks!
I thanks it's not about error handling, it's a crash caused by accessing a null pointer.
And the situation of each crash may be different.
