### ISSUE TITLE
Sometimes it does nothing...

### ISSUE THREAD

**Issue by YoggSaronn** [vesoft-inc/nebula-importer#254]
When uses mebula-importer docker in k8s, it runs successfully first but got no info and doesn't create a new space in second time, also it is sure for dropping existing space, and we ues UUID for creating new space name. Does anyone know how to fix this problem?

<img width="881" alt="微信图片_20221216093657" src="https://user-images.githubusercontent.com/38631672/208002089-6e23b436-adf2-420d-91fc-f11973b5313b.png">

**Comment by veezhang** [comment]
@YoggSaronn Hi, can you provide some information?

- nebula-importer version
- NebulaGraph version
- nebula-importer configuration file
- a few lines of csv data
- the steps that caused the problem.

**Comment by QingZ11** [comment]
We have noticed that the issue you created hasn’t been updated for nearly a month, so we have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊
