### ISSUE TITLE
Support IGNORE_EXISTED_INDEX

### ISSUE THREAD

**Issue by xiajingchun** [vesoft-inc/nebula-importer#262]
**Introduction**

When there're indexes defined in the space schema, the performance of inserting new data will be impacted significantly. The more indexes are defined, the worse the performance will become.

Can we add a flag in importer to enable the IGNORE_EXISTED_INDEX feature which is supported in INSERT VERTEX and INSERT EDGE, as below:

```
INSERT VERTEX IGNORE_EXISTED_INDEX person(id) ...
INSERT EDGE IGNORE_EXISTED_INDEX like(grade) ...
```

This flag can be configured globally and defined by vertex type and edge type. 

**Contents**

**Related work**

**Comment by veezhang** [comment]
#264
