### ISSUE TITLE
support delete

### ISSUE THREAD

**Issue by veezhang** [vesoft-inc/nebula-importer#273]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wey-gu** [comment]
delete was supported in last version with the label `-`, just in case it's not aware of.

cc @HarrisChu

**Comment by HarrisChu** [comment]
still doubt the user case...

**Comment by wey-gu** [comment]
> still doubt the user case...

I actually had been seeing users asking about this(last night there is one, already).

I was thinking that you mentioned there are almost no users using it, but maybe not that few, and some users don't know it's possible as it's not highlighted enough in docs or so?

**Comment by veezhang** [comment]
The previous method required modifying the file, which is usually relatively large, and it is not suitable to modify it casually.
And now add `mode` in configuration file  to support it now.
The default value is `INSERT`,  optionally `INSERT`, `UPDATE`, `DELETE`.

**Comment by veezhang** [comment]
> still doubt the user case...

This is what a customer delivery project needs, a temporary and urgent implementation.

**Comment by wey-gu** [comment]
This method(without needing modification on csv files)is more general to me,👍
