### ISSUE TITLE
"sources.edges.filter.expr" doesn't work in nebula-importer-4.0.0

### ISSUE THREAD

**Issue by marcus-Tian** [vesoft-inc/nebula-importer#300]
I set `sources.edges.filter.expr: expr: Record[4] != ""` in yaml file, then run nebula-importer. The procedure succeeded with no error or warning, but i checked the data imported into graph, the filter expression didn't work, the record with `Record[4]==""` was imported to database.

**Linux 3.10.0-1127.18.2.el7.x86_64**
**nebula-importer-4.0.0**
**nebulaGraph-3.6.0**

1. prepare csv file 《sample.csv》
2. prepare yaml file 《sample.yaml》
3. ./bin/nebula-importer --config sample.yaml 
4. searching in studio with command ``match (n:PERSON)-[e:WORK]->(m:PERSON) where id(n)=="333" return e;``

![image](https://github.com/vesoft-inc/nebula-importer/assets/52765713/8046ed07-c3ea-495f-a44b-a67d222aa390)

referred files:
1、《sample.csv》
[sample.csv](https://github.com/vesoft-inc/nebula-importer/files/13548502/sample.csv)
2、《sample.yaml》
[sample.txt](https://github.com/vesoft-inc/nebula-importer/files/13548546/sample.txt)

**Comment by wey-gu** [comment]
@veezhang could this be related to "" vs NULL?

**Comment by veezhang** [comment]
@marcus-Tian Hi, the `filter` is supported starting from `4.1.0`, maybe you need upgrade the `nebula-importer`.
U can download in the [`releases`](https://github.com/vesoft-inc/nebula-importer/releases) page.
cc @wey-gu

**Comment by QingZ11** [comment]
Hi, I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊
