### ISSUE TITLE
go环境搭建的坑

### ISSUE THREAD

**Issue by qzd147** [vesoft-inc/nebula-importer#36]
千万不能sudo apt-get install golang，要找一个靠谱的教程

**Comment by jievince** [comment]
对，apt下载的go版本太旧了，必须去官网下载最新的包（version>=1.13)
https://github.com/vesoft-inc/nebula-importer/blob/master/docs/golang-install.md

**Comment by yixinglu** [comment]
Before you install golang package in ubuntu, you can use `apt-cache show golang` to check the package version.
