### ISSUE TITLE
有两个文件 path可以写两个么？

### ISSUE THREAD

**Issue by jingyan6** [vesoft-inc/nebula-importer#81]
![image](https://user-images.githubusercontent.com/13622607/86994305-a85d3980-c1d8-11ea-96d2-7f80d2e3573b.png)

**Comment by yixinglu** [comment]
现在还不支持同一个 schema 读取多个文件。目前还只能逐个文件来配置。后期考虑一个文件夹下的所有相同schema 文件的导入。

**Comment by IanSmith123** [comment]
https://github.com/vesoft-inc/nebula-importer/pull/153  增加了对通配符文件名的支持，此处可以写 `. ./csv/edge/user_product_visit*.csv` 导入相同结构的多个文件。
