### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by sliontc** [vesoft-inc/nebula-importer#96]
When I build the importer, something wrong happened:

[root@COS nebula-importer]# make build
rm -rf nebula-importer;
go: github.com/vesoft-inc/nebula-go@v1.1.0: Get "https://proxy.golang.org/github.com/vesoft-inc/nebula-go/@v/v1.1.0.mod": dial tcp 172.217.160.81:443: i/o timeout
make: *** [fmt] 错误 1

How can I change the file location with local file?

**Comment by sevenseablue** [comment]
this is a go proxy problem. who not familar with go will meet this problem.  that is, go  has a proxy defalt which in China not connected. make another proxy.
https://github.com/ethereum/go-ethereum/issues/21129

solution: https://goproxy.cn/
`$ go env -w GO111MODULE=on
$ go env -w GOPROXY=https://goproxy.cn,direct`
